ARG CONTAINER=openwrt/sdk
ARG ARCH=mips_24kc
FROM $CONTAINER:$ARCH

RUN sudo apt-get install --assume-yes apt-utils
RUN curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - && \
    sudo apt-get install -y nodejs
LABEL "com.github.actions.name"="OpenWrt SDK"

ADD entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]
