ARG CONTAINER=openwrt/sdk
ARG ARCH=mips_24kc
FROM $CONTAINER:$ARCH AS base

ENV ARCH=$ARCH

LABEL "com.github.actions.name"="OpenWrt SDK"

ADD open_sdk.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]