ARG CONTAINER=openwrtorg/sdk
FROM $CONTAINER:ipq40xx-generic-18.06.4

ENV ARCH=$ARCH

LABEL "com.github.actions.name"="OpenWrt SDK"
ADD mbedtls-2.12.0-gpl.tgz /home/build/
ADD glinet_sdk.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
