name: glinet build
on: workflow_dispatch
env:
  REPO_URL: https://github.com/innet8/rtty.git
  REPO_BRANCH: openwrt-package

jobs:
  build:
    name: Build ${{ matrix.arch }} ipk
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - ipq_ipq40xx-qsdk11

    steps:
      - uses: actions/checkout@v3

      - name: Add test directories
        run: mkdir artifacts feed

      - name: Build
        uses: innet8/gh-action-sdk@master
        env:
          ARCH: ${{ matrix.arch }}
          ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
          FEED_DIR: ${{ github.workspace }}/feed
          MODE: glinet
          DEPENDENCES: libev libopenssl libmbedtls zlib
          ADDR: ${{ env.REPO_URL }}
          BRANCH: ${{ env.REPO_BRANCH }}
          PKG: rtty

      - name: Store packages
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch}}-packages
          path: bin/ipq/packages/base/rtty*.ipk
