name: Test

on:
  pull_request:

env:
  REPO_URL: https://github.com/zzzzzhy/lede.git
  REPO_BRANCH: master

jobs:
  build:
    name: Test ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - ipq
          - mips_24kc-19.07
          - x86_64

    steps:
      - uses: actions/checkout@v3

      - name: Add test directories
        run: mkdir artifacts feed

      - name: Build
        uses: innet8/gh-action-sdk@composite
        env:
          ARCH: ${{ matrix.arch }}-master
          ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
          FEED_DIR: ${{ github.workspace }}/feed
          MODE: only_custom
          DEPENDENCES: libev libopenssl libmbedtls zlib
          ADDR: $REPO_URL
          BRANCH: $REPO_BRANCH
          PKG: rtty

      - name: Verify packages saved
        run: find artifacts/bin/packages/${{ matrix.arch }}/packages/ -maxdepth 1 -name '*.ipk' -type f | grep .

      - name: Verify logs saved
        run: find artifacts/logs/package/feeds/packages/ -mindepth 2 -maxdepth 2 -name compile.txt -type f | grep .
